"""empty message

Revision ID: c8a67c069f5f
Revises: None
Create Date: 2016-11-16 00:54:05.366641

"""

# revision identifiers, used by Alembic.
revision = 'c8a67c069f5f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
